"""SQLite persistence (package facade). Submodules: core, users, areas, marketplace, history, copytrade, journal, agents, push, audit.

Every name used elsewhere as ``db.x`` is re-exported here. Module-level state
that is *reassigned* (the init flag, the user count, the area-id cache, the areas
generation) lives in ``core`` and is reached through its functions
(``mark_uninitialized``, ``user_count``, ``all_area_ids``, ``areas_generation``)."""
from __future__ import annotations

from . import core, users, areas, marketplace, history, copytrade, journal, agents, push, audit  # noqa: F401
from .core import (  # noqa: F401
    ROOT_DIR,
    DATA_DIR,
    DB_FILE,
    _init_lock,
    areas_generation,
    FEATURES,
    default_area_features,
    _all_features_on,
    _now,
    _local,
    _connect,
    _users,
    _pw_versions,
    _primary_area,
    reset_caches,
    init,
    meta_get,
    meta_set,
    user_count,
    all_area_ids,
    _active_subs,
    _sub_counts,
    _features_cache,
    _agents_by_hash,
    _agent_touch_at,
    _bump_areas_generation,
    mark_uninitialized,
    set_db_file,
)
from .users import (  # noqa: F401
    hash_password,
    verify_password,
    _row_to_user,
    record_login,
    get_user,
    get_user_by_email,
    _DUMMY_HASH,
    authenticate,
    list_users,
    create_user,
    set_password,
    password_version,
    revoke_sessions,
    authenticate_async,
    create_user_async,
    set_password_async,
    consume_password_reset_async,
    mfa_secret,
    mfa_begin,
    mfa_enable,
    mfa_counter,
    mfa_touch_counter,
    mfa_reset,
    mfa_set_backup_codes,
    mfa_backup_codes_left,
    mfa_use_backup_code,
    delete_user,
    area_owner_email,
    user_features,
    create_invite,
    get_invite,
    list_invites,
    consume_invite,
    delete_invite,
    create_password_reset,
    get_password_reset,
    consume_password_reset,
)
from .areas import (  # noqa: F401
    user_primary_area,
    user_area_ids,
    get_area,
    get_area_settings_raw,
    get_area_settings,
    save_area_settings,
    encrypt_existing_settings,
    area_owner,
    _load_features,
    get_area_features,
    set_area_feature,
    backfill_alert_emails,
)
from .marketplace import (  # noqa: F401
    _subs_changed,
    _row_to_sub,
    upsert_subscription,
    set_subscription_status,
    SUB_STATUSES,
    get_subscription,
    update_subscription,
    delete_subscription,
    delete_subscriptions_for_webhook,
    list_subscriptions,
    list_subscribers,
    subscriber_counts,
    active_subscriptions,
)
from .history import (  # noqa: F401
    _json,
    insert_signal,
    insert_order,
    _signal_row,
    _order_row,
    list_signals,
    list_orders,
    history_stats,
    signal_stats,
    signal_latencies,
    count_signal_outcomes,
    prune_history,
)
from .copytrade import (  # noqa: F401
    insert_copy_event,
    list_copy_events,
    _TWIN_COLS,
    save_copy_twin,
    delete_copy_twin,
    delete_copy_twins,
    list_copy_twins,
    save_copy_state,
    delete_copy_state,
    list_copy_state,
    prune_copy_events,
)
from .journal import (  # noqa: F401
    _TRADE_COLS,
    upsert_journal_fill,
    journal_fills_for,
    upsert_journal_trade,
    find_similar_journal_trade,
    _SOURCE_RANK,
    dedupe_journal_trades,
    _trade_row,
    list_journal_trades,
    get_journal_trade,
    update_journal_trade_note,
    journal_accounts,
    journal_symbols,
    upsert_journal_snapshot,
    list_journal_snapshots,
    insert_journal_import,
    journal_unseen,
    journal_mark_seen,
    list_journal_imports,
)
from .agents import (  # noqa: F401
    AGENT_PAIRING_TTL_S,
    _agent_hash,
    _row_to_agent,
    create_agent_pairing,
    consume_agent_pairing,
    create_agent,
    get_agent_by_token,
    get_agent,
    list_agents,
    touch_agent,
    rename_agent,
    delete_agent,
)
from .push import (  # noqa: F401
    _row_to_push,
    upsert_push_subscription,
    list_push_subscriptions,
    delete_push_subscription,
    delete_push_subscription_by_endpoint,
    touch_push_subscription,
)
from .audit import (  # noqa: F401
    log_action,
    LOGIN_ACTIONS,
    list_audit,
)
