@echo off
REM ===========================================================================
REM  Tradovate Webhook Bridge - Windows installer
REM
REM  Creates an isolated virtual environment, installs dependencies, and writes
REM  a start.bat launcher. Double-click this file or run it from a terminal.
REM ===========================================================================
setlocal enabledelayedexpansion
cd /d "%~dp0"

echo.
echo   Tradovate Webhook Bridge - installer
echo   ------------------------------------
echo.

REM --- find a usable Python --------------------------------------------------
set "PY="
where py >nul 2>&1 && set "PY=py -3"
if not defined PY (
  where python >nul 2>&1 && set "PY=python"
)
if not defined PY (
  echo  [X] Python was not found.
  echo      Install Python 3.9+ from https://www.python.org/downloads/windows/
  echo      During setup, tick "Add python.exe to PATH".
  echo.
  pause
  exit /b 1
)

for /f "tokens=2" %%v in ('%PY% --version 2^>^&1') do set "PYVER=%%v"
echo  [ok] Using Python %PYVER%

REM --- create the virtual environment ---------------------------------------
echo.
echo  ==^> Creating virtual environment in .venv
%PY% -m venv .venv
if errorlevel 1 (
  echo  [X] Failed to create the virtual environment.
  pause
  exit /b 1
)

call .venv\Scripts\activate.bat

echo  ==^> Upgrading pip and installing dependencies
python -m pip install --quiet --upgrade pip
python -m pip install --quiet -r requirements.txt
if errorlevel 1 (
  echo  [X] Failed to install dependencies.
  pause
  exit /b 1
)
echo  [ok] Dependencies installed

REM --- write the launcher ----------------------------------------------------
echo  ==^> Writing launcher: start.bat
(
  echo @echo off
  echo REM Auto-generated by install.bat - starts the Tradovate Webhook Bridge.
  echo cd /d "%%~dp0"
  echo call .venv\Scripts\activate.bat
  echo if "%%PORT%%"=="" set PORT=8000
  echo python run.py
  echo pause
) > start.bat
echo  [ok] Launcher written

echo.
echo  [ok] Installation complete!
echo.
echo    Start the bridge:   double-click start.bat  (or run it in a terminal)
echo    Open the dashboard: http://localhost:8000
echo    Open the Setup Guide tab in the dashboard for next steps.
echo.
pause
