#!/usr/bin/env bash
#
# Tradovate Webhook Bridge — Linux / macOS installer
#
# Creates an isolated virtual environment, installs dependencies, and writes a
# launcher. Optionally installs a systemd service so the bridge starts on boot.
#
#   ./install.sh                 # install into ./.venv
#   ./install.sh --service       # also install a systemd user service (Linux)
#   ./install.sh --port 9000     # set the port the launcher uses
#
set -euo pipefail

# --- locate ourselves -------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

PORT=6000
INSTALL_SERVICE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --service) INSTALL_SERVICE=1; shift ;;
    --port) PORT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

c_green=$'\033[32m'; c_blue=$'\033[34m'; c_yellow=$'\033[33m'; c_reset=$'\033[0m'
say()  { printf "%s==>%s %s\n" "$c_blue" "$c_reset" "$1"; }
ok()   { printf "%s ok %s %s\n" "$c_green" "$c_reset" "$1"; }
warn() { printf "%s !! %s %s\n" "$c_yellow" "$c_reset" "$1"; }

echo
echo "  Tradovate Webhook Bridge — installer"
echo "  ------------------------------------"
echo

# --- find a usable Python ---------------------------------------------------
PYTHON=""
for cand in python3.12 python3.11 python3 python; do
  if command -v "$cand" >/dev/null 2>&1; then
    ver="$("$cand" -c 'import sys;print("%d.%d"%sys.version_info[:2])' 2>/dev/null || echo 0)"
    major="${ver%%.*}"; minor="${ver##*.}"
    if [[ "$major" == "3" && "$minor" -ge 9 ]]; then PYTHON="$cand"; break; fi
  fi
done
if [[ -z "$PYTHON" ]]; then
  warn "Python 3.9+ not found. Install it first:"
  echo "    Debian/Ubuntu : sudo apt install python3 python3-venv python3-pip"
  echo "    Fedora        : sudo dnf install python3 python3-pip"
  echo "    macOS         : brew install python"
  exit 1
fi
ok "Using $("$PYTHON" --version) ($PYTHON)"

# --- create / refresh the virtual environment -------------------------------
say "Creating virtual environment in .venv"
"$PYTHON" -m venv .venv
# shellcheck disable=SC1091
source .venv/bin/activate
ok "Virtual environment ready"

say "Upgrading pip and installing dependencies"
python -m pip install --quiet --upgrade pip
python -m pip install --quiet -r requirements.txt
ok "Dependencies installed"

# --- write a launcher -------------------------------------------------------
say "Writing launcher: start.sh"
cat > start.sh <<EOF
#!/usr/bin/env bash
# Auto-generated by install.sh — starts the Tradovate Webhook Bridge.
cd "\$(dirname "\${BASH_SOURCE[0]}")"
source .venv/bin/activate
export PORT="\${PORT:-$PORT}"
exec python run.py
EOF
chmod +x start.sh
ok "Launcher written (PORT=$PORT)"

# --- optional systemd user service -----------------------------------------
if [[ "$INSTALL_SERVICE" == "1" ]]; then
  if command -v systemctl >/dev/null 2>&1; then
    say "Installing systemd user service"
    mkdir -p "$HOME/.config/systemd/user"
    SERVICE_FILE="$HOME/.config/systemd/user/tradovate-bridge.service"
    cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Tradovate Webhook Bridge
After=network-online.target

[Service]
WorkingDirectory=$SCRIPT_DIR
Environment=PORT=$PORT
ExecStart=$SCRIPT_DIR/.venv/bin/python $SCRIPT_DIR/run.py
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
    systemctl --user daemon-reload
    systemctl --user enable --now tradovate-bridge.service || warn "Could not enable service (is the user session active?)"
    ok "Service installed: systemctl --user status tradovate-bridge"
  else
    warn "systemctl not available — skipping service install"
  fi
fi

echo
ok "Installation complete!"
echo
echo "  Start the bridge:   ./start.sh"
echo "  Open the dashboard: http://localhost:$PORT"
echo "  Open the Setup Guide tab in the dashboard for next steps."
echo
